# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3b10fd023326e4dc193b82d6ff1f499ec242f3657c29e8b582b051caea161ca8f6babf966b79aa052f4af43e17ebf9ec245a347b1e507f82f174dd273bef62

test:
  secret_key_base: 5a77bcb0944334a0f91693a115f6d10c20d53ff4428a4f33ecc0899211dc159c60aa0ab87439ff833c4b203e245b97eea65b4054579117b340c977ffe6b41bf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
